#
# @see https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/
#

service: <%= name %>

provider:
  name: aws
  runtime: nodejs4.3

# Set env variables in the .env file
stage: ${env:SERVERLESS_STAGE}
region: ${env:SERVERLESS_REGION}


# NOTE: This doesn't act quite like serverless, which adds a ** to the start of your globs which
# massively slows down globbing. By default everything is excluded. See ./scripts/bundle.js for details.
package:
  include: 
    - node_modules/**
    - dist/**
    - prod.js
    - package.json


functions:
  <% if(graphql) { %>
  graphql:
    handler: ${env:SERVERLESS_STAGE}.graphqlApi
    events:
      - http:
          path: /
          method: post
          cors: true
  <% } else { %>
  demo:
    handler: ${env:SERVERLESS_STAGE}.demo
    events:
      - http:
          path: /
          method: get
  <% } %>

#   Add any plugins here
plugins:
  - serverless-offline

